### ISSUE TITLE
insert a new activity force to have time_start time_end

### ISSUE THREAD

**Issue by tigerfoot** [ioda-net/waffle-front#2] opened 2016-04-09 18:08 UTC
Beside the fact the two fields are optionnal is no value is entered, postgresql backend refuse to insert the row due to '' value in place of NULL
Can be more api related.

General rule : if a field is not varchar or text and has no value, use NULL for the database

General remark : datetimepicker should also permit to enter easily time in the field (for the moment only date is picked and rendered)

**Comment by Jenselme** [comment] 2016-04-13 13:28
Cannot reproduce

**Comment by Jenselme** [comment] 2016-04-13 13:49
Check that it is no strange constraint in your db.

**Comment by tigerfoot** [comment] 2016-04-13 15:20
There's nothing strange 

The query that is pass to postgresql is invalid
'''
  <h1>400 Bad Request</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
(psycopg2.DataError) invalid input syntax for type timestamp: &quot;&quot;
LINE 3: cpu ok&#x27;, &#x27;2016-04-13&#x27;, &#x27;&#x27;, &#x27;&#x27;, &#x27;0:15:00&#x27;, true, true) RETURN...
'''
'''sql
-- BAD
INSERT INTO waf.activities (project_id, user_id, subject, description, day_date, time_start, time_end, time_spent, billable, active) VALUES (117, 2, 'fix pending stash', 'Cleanup d''un stash en déshérance.', '2016-04-13', '', '', '0:30:00', true, true)
'''
'''sql
-- What is should be
INSERT INTO waf.activities (project_id, user_id, subject, description, day_date, time_start, time_end, time_spent, billable, active) VALUES (117, 2, 'fix pending stash', 'Cleanup d''un stash en déshérance.', '2016-04-13', NULL, NULL, '0:30:00', true, true)
'''

'''sql
CREATE TABLE activities
(
  id bigserial NOT NULL, -- Unique id for activity
  project_id bigint NOT NULL, -- Foreign key to projects id - Describe to what project activity is related
  user_id integer NOT NULL, -- Foreign key to users id - Describe Who
  subject character varying(64) NOT NULL, -- Short summary of the activity...
  description text, -- Long description longue...
  day_date date NOT NULL DEFAULT now(), -- Day on which activity occur, by default NOW(), can't be null
  time_start timestamp without time zone, -- optionnal date and starting time....
  time_end timestamp without time zone, -- optionnal date and ending time....
  time_spent interval NOT NULL, -- Time spent on the activity....
  billable boolean NOT NULL DEFAULT true, -- Boolean to indicate if this will be billed (default TRUE ) or not free (FALSE)....
  active boolean NOT NULL DEFAULT true, -- Boolean flag which indicate if the activity if the activity has to be included in the next report and invoice ( TRUE ) so active....
  CONSTRAINT pkey_activite PRIMARY KEY (id),
  CONSTRAINT fkey_activities_projects FOREIGN KEY (project_id)
      REFERENCES projects (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION, -- Foreign key for project, any activity has to be linked to an existing project id...
  CONSTRAINT fkey_activities_users FOREIGN KEY (user_id)
      REFERENCES users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE activities
  OWNER TO waffle_dba;
COMMENT ON TABLE activities
  IS 'Store activities, linked to projects, users';
COMMENT ON COLUMN activities.id IS 'Unique id for activity';
COMMENT ON COLUMN activities.project_id IS 'Foreign key to projects id - Describe to what project activity is related';
COMMENT ON COLUMN activities.user_id IS 'Foreign key to users id - Describe Who';
COMMENT ON COLUMN activities.subject IS 'Short summary of the activity
Used on reports as a subtitle.';
COMMENT ON COLUMN activities.description IS 'Long description longue
Can be optionnal.
Store any kind of useful and detailled informations.
This field is used in reports';
COMMENT ON COLUMN activities.day_date IS 'Day on which activity occur, by default NOW(), can''t be null';
COMMENT ON COLUMN activities.time_start IS 'optionnal date and starting time.
can be null (by default)';
COMMENT ON COLUMN activities.time_end IS 'optionnal date and ending time.
can be null (by default)';
COMMENT ON COLUMN activities.time_spent IS 'Time spent on the activity.
[@] quantity unit [quantity unit...] [direction]
Can be the substraction of time_end by time_start';
COMMENT ON COLUMN activities.billable IS 'Boolean to indicate if this will be billed (default TRUE ) or not free (FALSE).
Control field used during building report for invoices';
COMMENT ON COLUMN activities.active IS 'Boolean flag which indicate if the activity if the activity has to be included in the next report and invoice ( TRUE ) so active.
or if it has been already billed (FALSE).
Used during reports and invoices building';

COMMENT ON CONSTRAINT fkey_activities_projects ON activities IS '
Foreign key for project, any activity has to be linked to an existing project id
Which then define it''s price
';


'''

**Comment by Jenselme** [comment] 2016-04-13 16:12
Fixed in 6ad845955c49ef3658f818a4b96ae3a025fbc43d

**Closed by Jenselme** 2016-04-13 16:12 UTC
Labels: bug
